config/routes.rb
Rails.application.routes.draw do
  resources :results

  resources :representments 
 
  resources :collections do
    member do
      get "learn"
      get "show_including_answers"
    end
  end
  
  resources :answers

  resources :questions do
    member do
      get "ask"
      patch "compare"
    end
    
    collection do
      get "learn"
    end  
  end  

  root 'collections#index'

end

app/models/collection.rb
class Collection < ActiveRecord::Base

  has_many :questions
  has_many :representments
  
  validates_presence_of :name
  validates_presence_of :rep

end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  before_action :set_collection, only: [:show, :edit, :update, :destroy, :learn, :show_including_answers]

  # GET /collections
  # GET /collections.json
  def index
    @collections = Collection.all
  end

  # GET /collections/1
  # GET /collections/1.json
  def show
  end

  def show_including_answers
  end

  # GET /collections/new
  def new
    @collection = Collection.new
  end

  # GET /collections/1/edit
  def edit
  end
  
  def learn
    unless Representment.where(collection_id: @collection.id).any?
      Question.where(collection_id: @collection.id).each do |question|
        Representment.create(collection_id: @collection.id, 
                             question_id: question.id,
                             rate: @collection.rep) 
      end
    end
    latest_entry_date = Representment.where(collection_id: @collection.id).maximum(:created_at)
    Question.where(created_at: (latest_entry_date..Time.now), 
                   collection_id: @collection.id)
            .each do |question| 
      Representment.create(collection_id: @collection.id, 
                           question_id: question.id, 
                           rate: @collection.rep) 
     end
    
    random_question_number = rand(Representment.where(collection_id: @collection.id).count)
#      if rand(3) == 0 
#        rand(Question.where(collection_id: @collection.id).count)
#      else
#        rand(Representment.where(collection_id: @collection.id).count)
#      end
      
    question_id = Representment.where(collection_id: @collection.id)[random_question_number].question_id
    
    redirect_to ask_question_path(question_id) 
  end

  # POST /collections
  # POST /collections.json
  def create
    @collection = Collection.new(collection_params)

    respond_to do |format|
      if @collection.save
        format.html { redirect_to @collection, notice: 'Collection was successfully created.' }
        format.json { render :show, status: :created, location: @collection }
      else
        format.html { render :new }
        format.json { render json: @collection.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /collections/1
  # PATCH/PUT /collections/1.json
  def update
    respond_to do |format|
      if @collection.update(collection_params)
        format.html { redirect_to @collection, notice: 'Collection was successfully updated.' }
        format.json { render :show, status: :ok, location: @collection }
      else
        format.html { render :edit }
        format.json { render json: @collection.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /collections/1
  # DELETE /collections/1.json
  def destroy
    @collection.destroy
    respond_to do |format|
      format.html { redirect_to collections_url, notice: 'Collection was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_collection
      @collection = Collection.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def collection_params
      params.require(:collection).permit(:name, :rep)
    end
end

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/views/collections/_form.html.erb
<%= form_for(@collection) do |f| %>
  <% if @collection.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@collection.errors.count, "error") %> prohibited this collection from being saved:</h2>

      <ul>
      <% @collection.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :rep %><br>
    <%= f.text_field :rep %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/collections/edit.html.erb
<h1>Editing collection</h1>

<%= render 'form' %>

<%= link_to 'Show', @collection %> |
<%= link_to 'Back', collections_path %>

app/views/collections/index.html.erb
<h1>Listing collections (all)</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @collections.each do |collection| %>
      <tr>
        <td><%= collection.name %></td>
        <td><%= collection.rep %></td>
        <td><%= link_to 'Learn', learn_collection_path(collection) %></td>
        <td><%= link_to 'Show', collection %></td>
        <td><%= link_to 'Show with answers', show_including_answers_collection_path(collection) %></td>
        <td><%= link_to 'Edit', edit_collection_path(collection) %></td>
        <td><%= link_to 'Destroy', collection, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Collection', new_collection_path %>

app/views/collections/new.html.erb
<h1>New collection</h1>

<%= render 'form' %>

<%= link_to 'Back', collections_path %>

app/views/collections/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @collection.name %>
</p>

<p>
  <strong>Repetition:</strong>
  <%= @collection.rep %>
</p>


<p>  
  <%= link_to 'New Question', new_question_path %>
</p>

<hr>

<% @collection.questions.each do |question| %>
  <p>
    <strong>Frage:</strong>
    <%= question.content %>
  </p>
  <p>
    <%= link_to 'Show', question %>
    <%= link_to 'Edit', edit_question_path(question) %>
    <%= link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?' } %>
  </p>  

<% end %>  

<hr>

<p>  
  <%= link_to 'New Question', new_question_path %>
</p>

<p>
  <%= link_to 'Back to Collections', collections_path %>
</p>  

app/views/collections/show_including_answers.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @collection.name %>
</p>

<hr>

<% @collection.questions.each do |question| %>

  <div style="page-break-inside: avoid;">
    <p>
      <strong>Frage:</strong>
      <%= question.content %> <br/>
      Quelle: 
      <%= question.reference %>

    </p>
    <% question.answers.each do |answer| %>
      <%= answer.correct ? " ☑ " : " ☐ " %> 
      <%= answer.content %> <br/>

    <% end %>
  </div>
<% end %>  