config/routes.rb
Rails.application.routes.draw do
  resources :results

  resources :representments 
 
  resources :collections do
    member do
      get "learn"
      get "show_including_answers"
    end
  end
  
  resources :answers

  resources :questions do
    member do
      get "ask"
      patch "compare"
    end
    
    collection do
      get "learn"
    end  
  end  

  root 'collections#index'

end

app/models/question.rb
# klassen in ruby mit grossbuchstaben 
class Question < ActiveRecord::Base

# relation mehrere answers auf eine question
# bezeichnung eines symboles beginnt mit doppelpunkt
# symbole in ruby mit kleinbuchstaben
  has_many :answers
  accepts_nested_attributes_for :answers
  belongs_to :collection
  
  validates_presence_of :collection, :content
  
  has_one :representment
  
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy, :ask, :compare]

  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
  end

  def ask
  end

  def compare
    @points = 0
 
    @given = {}

    params[:question][:answers_attributes].each do |key, value|
      if value[:correct] == "1"
        correct = true
      else
        correct = false
      end
      
      if Answer.find(value[:id]).correct == correct
        @points = @points + 1
      end
          
      @given[value[:id].to_i] = correct
    end
    
    @representment = Representment.where(question_id: @question.id).first
    unless @representment
      @representment = Representment.create(rate: 1, 
                                            question_id: @question.id, 
                                            collection_id: @question.collection_id)
    end
    if @points == 5
      if @representment.rate == 1
        @representment.delete
      else
        @representment.update(rate: @representment.rate - 1)
      end  
    else 
      @representment.update(rate: @question.collection.rep)
    end
    @unanswered = Representment.where(rate: 3, 
                                      collection_id: @question.collection_id).count        
 
    @answered_once = Representment.where(rate: 2, 
                                      collection_id: @question.collection_id).count         
 
    @answered_twice = Representment.where(rate: 1, 
                                      collection_id: @question.collection_id).count        
    Result.create(question_id: @question.id, 
               collection_id: @question.collection_id, 
               points: @points)
  end

  # GET /questions/new
  def new
    @question = Question.new
  # zusammenhängen mit schleife
    [1, 2, 3, 4, 5].each do
      @question.answers << Answer.new
    end
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question.collection, notice: 'Question was successfully created.' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question.collection, notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:content, :reference, :collection_id,
                        answers_attributes:[:content, :correct, :comment, :id] )
    end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<%= simple_form_for(@question) do |f_question| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f_question.text_area :content, style: "width:100%", placeholder: "content" %>
    <br>
    <%= f_question.text_field :reference, style: "width:100%", placeholder: "reference" %>
    <br>
    <%= f_question.association :collection %>
  </div>

  <%# schleife %>
  <h2> Antworten </h2>
  <%= f_question.fields_for :answers do |f_answer| %>
    <strong> Antwort <%= f_answer.index + 1 %> </strong>
      <%= f_answer.label :correct %>
      <%= f_answer.check_box :correct %>
    <div class="field">
      <%= f_answer.text_area :content, style: "width:100%", placeholder: "content"  %>
      <br>
      <%= f_answer.text_field :comment, style: "width:100%", placeholder: "comment" %>
    </div>
  <% end %>


  <div class="actions">
    <%= f_question.submit %>
  </div>
<% end %>

app/views/questions/ask.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong> <%= @question.content %> </strong>
</p>

<%= form_for(@question, url: {action: :compare} ) do |f_question| %>

  <% @question.answers.shuffle.each do |answer| %>
    <%= f_question.fields_for :answers,answer do |f_answer| %>
      <p>
        <%= f_answer.check_box :correct, checked: false %>
        <%= answer.content %>
      </p>
    <% end %>
  <% end %>

  <div class="actions">
    <%= f_question.submit "compare answers" %>
  </div>

  <%= link_to "edit question", edit_question_path(@question) %>

<% end %>

app/views/questions/compare.html.erb
<p id="notice"><%= notice %></p>

<p>
  Result: <strong> <%= @points %> </strong> points 
  <br>
  <strong><%= @unanswered %></strong> questions unanswered, 
  <strong><%= @answered_once %></strong> questions answered once, 
  <strong><%= @answered_twice %></strong> questions answered twice
  <%= link_to 'Next Question', learn_collection_path(@question.collection) %> 
</p>

  <strong> <%= @question.content %> </strong> <br>

<% @question.answers.each do |answer| %>
  <hr> 
  <p>
    <%= answer.content %> 
    <br> 
    correct answer <strong> <%= answer.correct %> </strong> 
    your answer <strong> <%= @given[answer.id] %> </strong>
    <br> 
    Comment: <%= answer.comment %>
  </p>

<% end %>

app/views/questions/edit.html.erb
<h1>Editing question</h1>

<%= render 'form' %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<h1>Listing questions</h1>

<%= link_to 'New Question', new_question_path %>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>Reference</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @questions.each do |question| %>
      <tr>
        <td><%= question.content %></td>
        <td><%= question.reference %></td>
        <td><%= link_to 'Show', question %></td>
        <td><%= link_to 'Edit', edit_question_path(question) %></td>
        <td><%= link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Question', new_question_path %>

<%= link_to 'Learning', learn_questions_path %>

app/views/questions/new.html.erb
<h1>New question</h1>

<%= render 'form' %>

<%= link_to 'Back', questions_path %>

app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @question.content %> <br>
  <strong>Reference:</strong>
  <%= @question.reference %> <br>
  <strong>Collection:</strong>
  <%= @question.collection.name if @question.collection %>
</p>

<% @question.answers.each do |answer| %>
  <hr> 
  <p>
    <strong>Content:</strong>
    <%= answer.content %> <br>
    <strong>Correct:</strong>
    <%= answer.correct %> <br>
    <strong>Comment:</strong>
    <%= answer.comment %>
  </p>

<% end %>

<%= link_to 'Edit', edit_question_path(@question) %> |
<%= link_to 'Back', questions_path %>