config/routes.rb
Rails.application.routes.draw do
  resources :results

  resources :representments 
 
  resources :collections do
    member do
      get "learn"
      get "show_including_answers"
    end
  end
  
  resources :answers

  resources :questions do
    member do
      get "ask"
      patch "compare"
    end
    
    collection do
      get "learn"
    end  
  end  

  root 'collections#index'

end

app/models/representment.rb
class Representment < ActiveRecord::Base

  belongs_to :question
  belongs_to :collection
  
end

app/controllers/representments_controller.rb
class RepresentmentsController < ApplicationController
  before_action :set_representment, only: [:show, :edit, :update, :destroy]

  # GET /representments
  # GET /representments.json
  def index
    @representments = Representment.all
  end

  # GET /representments/1
  # GET /representments/1.json
  def show
  end

  # GET /representments/new
  def new
    @representment = Representment.new
  end

  # GET /representments/1/edit
  def edit
  end

  # POST /representments
  # POST /representments.json
  def create
    @representment = Representment.new(representment_params)

    respond_to do |format|
      if @representment.save
        format.html { redirect_to @representment, notice: 'Representment was successfully created.' }
        format.json { render :show, status: :created, location: @representment }
      else
        format.html { render :new }
        format.json { render json: @representment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /representments/1
  # PATCH/PUT /representments/1.json
  def update
    respond_to do |format|
      if @representment.update(representment_params)
        format.html { redirect_to @representment, notice: 'Representment was successfully updated.' }
        format.json { render :show, status: :ok, location: @representment }
      else
        format.html { render :edit }
        format.json { render json: @representment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /representments/1
  # DELETE /representments/1.json
  def destroy
    @representment.destroy
    respond_to do |format|
      format.html { redirect_to representments_url, notice: 'Representment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_representment
      @representment = Representment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def representment_params
      params.require(:representment).permit(:user_id, :question_id, :collection_id, :rate)
    end
end

app/helpers/representments_helper.rb
module RepresentmentsHelper
end

app/views/representments/_form.html.erb
<%= simple_form_for(@representment) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :user_id %>
    <%= f.input :question_id %>
    <%= f.input :collection_id %>
    <%= f.input :rate %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/representments/edit.html.erb
<h1>Editing representment</h1>

<%= render 'form' %>

<%= link_to 'Show', @representment %> |
<%= link_to 'Back', representments_path %>

app/views/representments/index.html.erb
<h1>Listing representments</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Question</th>
      <th>Collection</th>
      <th>Rate</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @representments.each do |representment| %>
      <tr>
        <td><%= representment.user_id %></td>
        <td><%= representment.question_id %></td>
        <td><%= representment.collection_id %></td>
        <td><%= representment.rate %></td>
        <td><%= link_to 'Show', representment %></td>
        <td><%= link_to 'Edit', edit_representment_path(representment) %></td>
        <td><%= link_to 'Destroy', representment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Representment', new_representment_path %>

app/views/representments/new.html.erb
<h1>New representment</h1>

<%= render 'form' %>

<%= link_to 'Back', representments_path %>

app/views/representments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @representment.user_id %>
</p>

<p>
  <strong>Question:</strong>
  <%= @representment.question_id %>
</p>

<p>
  <strong>Collection:</strong>
  <%= @representment.collection_id %>
</p>

<p>
  <strong>Rate:</strong>
  <%= @representment.rate %>
</p>

<%= link_to 'Edit', edit_representment_path(@representment) %> |
<%= link_to 'Back', representments_path %>